# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lipsync_schema.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14lipsync_schema.proto\"E\n\x0bRequestData\x12\x13\n\x0bmessageuuid\x18\x01 \x01(\t\x12\x10\n\x04\x66\x61\x63\x65\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x0f\n\x03mel\x18\x03 \x03(\x02\x42\x02\x10\x01\"5\n\x0cResponseData\x12\x13\n\x0bmessageuuid\x18\x01 \x01(\t\x12\x10\n\x04\x66\x61\x63\x65\x18\x02 \x03(\x02\x42\x02\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lipsync_schema_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTDATA'].fields_by_name['face']._options = None
  _globals['_REQUESTDATA'].fields_by_name['face']._serialized_options = b'\020\001'
  _globals['_REQUESTDATA'].fields_by_name['mel']._options = None
  _globals['_REQUESTDATA'].fields_by_name['mel']._serialized_options = b'\020\001'
  _globals['_RESPONSEDATA'].fields_by_name['face']._options = None
  _globals['_RESPONSEDATA'].fields_by_name['face']._serialized_options = b'\020\001'
  _globals['_REQUESTDATA']._serialized_start=24
  _globals['_REQUESTDATA']._serialized_end=93
  _globals['_RESPONSEDATA']._serialized_start=95
  _globals['_RESPONSEDATA']._serialized_end=148
# @@protoc_insertion_point(module_scope)
